AUTH_SCHEME_BEARER = "Bearer"
AUTH_SCHEME_BEARER_LOWER = AUTH_SCHEME_BEARER.lower()

AUTHENTICATION_REQUIRED_MESSAGE = "인증 정보가 필요합니다."
AUTHENTICATION_FAILED_MESSAGE = "인증 정보가 올바르지 않습니다."
AUTHORIZATION_FORBIDDEN_MESSAGE = "접근 권한이 없습니다."
